import {TetrisEngine} from './engine.js';import {Renderer} from './renderer.js';import {Particles} from './particles.js';import {AudioSystem} from './audio.js';import {COLORS} from './pieces.js';
const $=s=>document.querySelector(s),board=$('#board'),effects=$('#effects'),particles=new Particles(),audio=new AudioSystem();
let engine,renderer,last=performance.now(),fall=0,running=false,displayScore=0,shake=0;
const emit=(name,data)=>{if(name==='hardDrop'){audio.play('drop');shake=7;for(const [x,y] of data.cells)particles.burst((x+.5)*36,(y+.5)*36,COLORS[engine.active.type],7,4);toast('IMPACT');}
 if(name==='lock')audio.play('lock');if(name==='lines'){audio.play(data.count===4?'tetris':'line');shake=data.count===4?12:3;data.rows.forEach(y=>{for(let x=0;x<10;x++)particles.burst((x+.5)*36,(y+.5)*36,'#fff',4,data.count===4?8:4)});toast(['','SINGLE','DOUBLE','TRIPLE','TETRIS!'][data.count],data.count===4);setTimeout(()=>engine.combo>0&&toast(`COMBO ×${engine.combo+1}`),450)}
 if(name==='level'){audio.play('level');toast(`LEVEL ${data.level}`,true);particles.burst(180,360,'#ffe75c',60,9)}if(name==='gameOver'){audio.play('over');shake=15;setTimeout(showGameOver,500)}};
function start(){engine=new TetrisEngine({onEvent:emit});renderer??=new Renderer(board,effects,particles);fall=0;displayScore=0;running=false;$('#menu').classList.remove('active');$('#game').classList.add('active');$('#pause-overlay').classList.remove('show');$('#over-overlay').classList.remove('show');countdown();sync();}
function countdown(){let items=['3','2','1','GO!'],i=0;const el=$('#countdown');el.classList.add('show');const tick=()=>{el.textContent=items[i++];el.classList.remove('pop');void el.offsetWidth;el.classList.add('pop');if(i<items.length)setTimeout(tick,600);else setTimeout(()=>{el.classList.remove('show');running=true;audio.setMusic(audio.music)},550)};tick();}
function toast(text,big=false){const el=$('#toast');el.textContent=text;el.className='toast show'+(big?' big':'');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='toast',850)}
function sync(){if(!engine)return;$('#level').textContent=String(engine.level).padStart(2,'0');$('#lines').textContent=String(engine.lines).padStart(2,'0');$('#best').textContent=String(localStorage.getItem('neon-tetris-best')||0).padStart(6,'0');$('#hold-lock').textContent=engine.canHold?'READY':'USED';$('#hold-lock').classList.toggle('used',!engine.canHold);renderer.preview($('#hold'),engine.hold);renderer.preview($('#next'),engine.bag.peek());}
function showGameOver(){running=false;const best=Math.max(engine.score,+(localStorage.getItem('neon-tetris-best')||0));localStorage.setItem('neon-tetris-best',best);$('#final-stats').innerHTML=`<p>SCORE <b>${engine.score}</b></p><p>LINES <b>${engine.lines}</b></p><p>LEVEL <b>${engine.level}</b></p>`;$('#over-overlay').classList.add('show');sync();}
function pause(){if(!running&&!engine?.paused)return;const paused=engine.togglePause();running=!paused;$('#pause-overlay').classList.toggle('show',paused);}
function action(key){if(!engine)return;if(key==='r'){start();return}if(key==='p'||key==='escape'){pause();return}if(!running)return;let ok=false;if(key==='arrowleft')ok=engine.move(-1,0);if(key==='arrowright')ok=engine.move(1,0);if(ok)audio.play('move');if(key==='arrowdown'){ok=engine.drop();if(ok)audio.play('soft')}if(key==='arrowup'||key==='x'){ok=engine.rotate(1);if(ok)audio.play('rotate')}if(key==='z'){ok=engine.rotate(-1);if(ok)audio.play('rotate')}if(key===' '){engine.hardDrop();fall=0}if(key==='c'||key==='shift'){ok=engine.holdPiece();if(ok)audio.play('hold')}sync();}
addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(['arrowleft','arrowright','arrowdown','arrowup',' ','shift'].includes(key))e.preventDefault();action(key)},{passive:false});
function loop(now){const dt=Math.min(40,now-last);last=now;if(engine&&running){fall+=dt;if(fall>=engine.gravityMs()){engine.drop();fall=0;sync()}displayScore+=(engine.score-displayScore)*Math.min(1,dt/180);$('#score').textContent=String(Math.round(displayScore)).padStart(6,'0');renderer.render(engine,dt);if(shake>0){$('#stage').style.transform=`translate(${(Math.random()-.5)*shake}px,${(Math.random()-.5)*shake}px)`;shake*=.84}else $('#stage').style.transform='';}else if(engine)renderer.render(engine,dt);requestAnimationFrame(loop)}requestAnimationFrame(loop);
$('#play').onclick=start;$('#again').onclick=start;$('#restart-pause').onclick=start;$('#resume').onclick=pause;$('#show-controls').onclick=()=>$('#controls-dialog').showModal();$('#close-controls').onclick=()=>$('#controls-dialog').close();
$('#music').onclick=e=>{audio.setMusic(!audio.music);e.currentTarget.querySelector('b').textContent=audio.music?'ON':'OFF'};$('#sfx').onclick=e=>{audio.sfx=!audio.sfx;e.currentTarget.querySelector('b').textContent=audio.sfx?'ON':'OFF'};$('#volume').oninput=e=>audio.volume=+e.target.value;
for(let i=0;i<55;i++){const s=document.createElement('i');s.style.cssText=`left:${Math.random()*100}%;top:${Math.random()*100}%;animation-delay:${Math.random()*5}s;opacity:${Math.random()*.5}`;$('#stars').append(s)}
