import{Game}from'./game.js';import{Renderer}from'./renderer.js';import{Particles}from'./particles.js';import{AudioSystem}from'./audio.js';import{COLORS}from'./pieces.js';
const $=s=>document.querySelector(s),canvas=$('#game'),particles=new Particles,audio=new AudioSystem;let game,renderer,last=0,displayScore=0,counting=false;
const high=()=>Number(localStorage.getItem('neon-tetris-high')||0),pad=(n,l=6)=>String(Math.floor(n)).padStart(l,'0');
function callout(text){const el=$('#callout');el.textContent=text;el.classList.remove('show');void el.offsetWidth;el.classList.add('show')}
function shake(){const el=$('#board-wrap');el.classList.remove('shake');void el.offsetWidth;el.classList.add('shake')}
function setup(){game=new Game({sound:n=>audio.play(n),hardDrop:(p,from,to)=>{shake();for(const[x,y]of p.cells)particles.burst((p.x+x+.5)*36,(to+y+.5)*36,COLORS[p.type],5,2.5)},lock:()=>{renderer.impact();audio.play('lock')},lines:(rows,n,combo)=>{renderer.flash(rows);rows.forEach(y=>particles.burst(180,(y+.5)*36,'#fff',n===4?40:20,n===4?5:3));callout(['','SINGLE','DOUBLE','TRIPLE','TETRIS!'][n]+(combo>0?`\nCOMBO ×${combo+1}`:''));audio.play(n===4?'tetris':combo>0?'combo':'line');if(n===4)shake()},level:n=>{callout(`LEVEL ${n}`);particles.burst(180,360,'#28e7ff',45,5);audio.play('level')},gameOver:()=>setTimeout(showGameOver,380)});renderer=new Renderer(canvas,game,particles);displayScore=0;updateUI()}
function updateUI(){if(!game)return;$('#score').textContent=pad(displayScore);$('#level').textContent=pad(game.level,2);$('#lines').textContent=pad(game.lines,2);$('#high-score').textContent=pad(Math.max(high(),game.score));$('#start-high').textContent=pad(high());$('#status').textContent=game.paused?'PAUSED':game.over?'OFFLINE':'RUNNING';$('#hold-state').textContent=game.holdUsed?'USED THIS TURN':'AVAILABLE · C / SHIFT';renderer.preview($('#next'),game.next);renderer.preview($('#hold'),game.hold,game.holdUsed)}
function loop(t){const dt=Math.min(35,t-last||16);last=t;if(game&&!counting){game.update(dt);particles.update(dt);renderer.draw(t,dt);displayScore+=(game.score-displayScore)*Math.min(1,dt/180);updateUI()}requestAnimationFrame(loop)}requestAnimationFrame(loop);
function countdown(){counting=true;const vals=['3','2','1','GO!'];vals.forEach((v,i)=>setTimeout(()=>{const e=$('#countdown');e.textContent=v;e.classList.remove('show');void e.offsetWidth;e.classList.add('show');if(i===3)setTimeout(()=>counting=false,550)},i*650))}
function start(){setup();$('#start-screen').classList.add('hidden');$('#game-screen').classList.remove('hidden');$('#pause-overlay').classList.add('hidden');$('#gameover-overlay').classList.add('hidden');countdown()}
function showGameOver(){audio.play('over');shake();particles.burst(180,300,'#ff5373',60,5);const best=Math.max(high(),game.score);localStorage.setItem('neon-tetris-high',best);$('#final-score').textContent=pad(game.score);$('#final-lines').textContent=game.lines;$('#final-level').textContent=game.level;$('#gameover-overlay').classList.remove('hidden')}
function pause(force){if(!game||game.over||counting)return;const paused=force??game.togglePause();if(force!==undefined)game.paused=force;$('#pause-overlay').classList.toggle('hidden',!paused);updateUI()}
addEventListener('keydown',e=>{if(!game||$('#game-screen').classList.contains('hidden'))return;const k=e.key.toLowerCase();if(['arrowleft','arrowright','arrowdown','arrowup',' ','shift'].includes(k))e.preventDefault();if(k==='p'||k==='escape')return pause();if(k==='r')return start();if(game.paused||game.over||counting)return;if(k==='arrowleft'){game.move(-1,0);audio.play('move')}else if(k==='arrowright'){game.move(1,0);audio.play('move')}else if(k==='arrowdown'){game.move(0,1);audio.play('soft')}else if(k==='arrowup'||k==='x')game.rotate(1);else if(k==='z')game.rotate(-1);else if(k===' ')game.hardDrop();else if(k==='c'||k==='shift')game.holdPiece()});
$('#play').onclick=start;$('#play-again').onclick=start;$('#resume').onclick=()=>pause(false);$('#restart-pause').onclick=start;$('#show-controls').onclick=()=>$('#controls-modal').classList.remove('hidden');$('#close-controls').onclick=()=>$('#controls-modal').classList.add('hidden');$('#sfx-toggle').onclick=e=>{audio.sfx=!audio.sfx;e.currentTarget.classList.toggle('active',audio.sfx);e.currentTarget.querySelector('span').textContent=`SFX ${audio.sfx?'ON':'OFF'}`};$('#music-toggle').onclick=e=>{const on=audio.toggleMusic();e.currentTarget.classList.toggle('active',on);e.currentTarget.querySelector('span').textContent=`MUSIC ${on?'ON':'OFF'}`};$('#volume').oninput=e=>audio.volume=+e.target.value;$('#start-high').textContent=pad(high());
