import{COLORS,SHAPES}from'./pieces.js';
export class Renderer{
 constructor(canvas,game,particles){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.game=game;this.particles=particles;this.cell=36;this.flashRows=[];this.impactUntil=0;this.lastX=game.current.x;this.visualX=this.lastX;this.visualY=game.current.y}
 block(ctx,x,y,color,alpha=1,scale=1){const s=this.cell,g=2,px=x*s+(s-s*scale)/2,py=y*s+(s-s*scale)/2,size=s*scale;ctx.save();ctx.globalAlpha=alpha;ctx.shadowColor=color;ctx.shadowBlur=alpha<.5?5:11;const grd=ctx.createLinearGradient(px,py,px+size,py+size);grd.addColorStop(0,'#fff');grd.addColorStop(.1,color);grd.addColorStop(1,this.shade(color,-35));ctx.fillStyle=grd;ctx.fillRect(px+g,py+g,size-g*2,size-g*2);ctx.shadowBlur=0;ctx.strokeStyle='rgba(255,255,255,.42)';ctx.lineWidth=1;ctx.strokeRect(px+g+1,py+g+1,size-g*2-2,size-g*2-2);ctx.fillStyle='rgba(255,255,255,.15)';ctx.fillRect(px+5,py+5,size-10,3);ctx.restore()}
 shade(hex,n){const v=parseInt(hex.slice(1),16),r=Math.max(0,(v>>16)+n),g=Math.max(0,((v>>8)&255)+n),b=Math.max(0,(v&255)+n);return`rgb(${r},${g},${b})`}
 grid(){const c=this.ctx,s=this.cell;c.strokeStyle='rgba(89,120,170,.075)';c.lineWidth=1;for(let x=0;x<=10;x++){c.beginPath();c.moveTo(x*s,0);c.lineTo(x*s,720);c.stroke()}for(let y=0;y<=20;y++){c.beginPath();c.moveTo(0,y*s);c.lineTo(360,y*s);c.stroke()}}
 draw(now,dt){const c=this.ctx;c.clearRect(0,0,360,720);this.grid();for(let y=0;y<20;y++)for(let x=0;x<10;x++)if(this.game.board[y][x])this.block(c,x,y,COLORS[this.game.board[y][x]],1,now<this.impactUntil?1.05:1);const p=this.game.current;if(!this.game.over){const gy=this.game.ghostY();for(const[x,y]of p.cells)this.block(c,p.x+x,gy+y,COLORS[p.type],.17);this.visualX+=(p.x-this.visualX)*Math.min(1,dt/55);this.visualY+=(p.y-this.visualY)*Math.min(1,dt/70);for(const[x,y]of p.cells)this.block(c,this.visualX+x,this.visualY+y,COLORS[p.type])}for(const f of this.flashRows){c.fillStyle=`rgba(255,255,255,${f.life})`;c.fillRect(0,f.y*this.cell,360,this.cell);f.life-=dt/280}this.flashRows=this.flashRows.filter(f=>f.life>0);this.particles.draw(c)}
 flash(rows){this.flashRows.push(...rows.map(y=>({y,life:.9})))} impact(){this.impactUntil=performance.now()+100}
 preview(canvas,type,dim=false){const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height;c.clearRect(0,0,w,h);if(!type)return;const cells=SHAPES[type],size=25,minX=Math.min(...cells.map(v=>v[0])),maxX=Math.max(...cells.map(v=>v[0])),minY=Math.min(...cells.map(v=>v[1])),maxY=Math.max(...cells.map(v=>v[1])),ox=(w-(maxX-minX+1)*size)/2,oy=(h-(maxY-minY+1)*size)/2;const old=this.cell;this.cell=size;for(const[x,y]of cells)this.block(c,ox/size+x-minX,oy/size+y-minY,COLORS[type],dim?.35:1);this.cell=old}
}
